### ISSUE TITLE
Authorization api_test fails on CentOS 7.3

### ISSUE THREAD

**Issue by learnMachining** [docker/go-plugins-helpers#96]
I cloned go-plugins-helpers code, also, I ran `go get github.com/go-plugins-helpers/sdk` to put the sdk code in $GOPATH. Then,  I went into the authorization directory and ran `go test -v` to execute authorization test. However,  10 minutes later, I got the message below:  

=== RUN   TestActivate
SIGQUIT: quit
PC=0x45e781 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x9021b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffdf4f50df8, 0x410bab, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:438 +0x21
runtime.futexsleep(0x9021b0, 0xc400000000, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0x9021b0)
	/usr/local/go/src/runtime/lock_futex.go:151 +0x9b
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1670 +0xe5
runtime.findrunnable(0xc42001f300, 0x0)
	/usr/local/go/src/runtime/proc.go:2125 +0x4d2
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2245 +0x12c
runtime.park_m(0xc42006aa80)
	/usr/local/go/src/runtime/proc.go:2308 +0xb6
runtime.mcall(0x7ffdf4f50f90)
	/usr/local/go/src/runtime/asm_amd64.s:286 +0x5b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42010e000, 0x754a32, 0xc, 0x767c90, 0x4868c6)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc42010e000)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc42010e000, 0xc42004dd78)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4200ec300, 0x8fc920, 0x4, 0x4, 0x7578cf)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42004df18, 0x768040)
	/usr/local/go/src/testing/testing.go:921 +0x111
_/home/captain/workspace/go-plugins-helpers/authorization.TestMain(0xc42004df18)
	/home/captain/workspace/go-plugins-helpers/authorization/api_test.go:205 +0xba
main.main()
	_/home/captain/workspace/go-plugins-helpers/authorization/_test/_testmain.go:48 +0xdb

goroutine 20 [select]:
net/http.(*persistConn).roundTrip(0xc4200a8b40, 0xc42006d080, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1970 +0x608
net/http.(*Transport).RoundTrip(0x8fd2a0, 0xc420112100, 0x8fd2a0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:413 +0x992
net/http.send(0xc420112100, 0x8c7600, 0x8fd2a0, 0x0, 0x0, 0x0, 0xc420078060, 0x100, 0xc420036c78, 0x1)
	/usr/local/go/src/net/http/client.go:249 +0x1a9
net/http.(*Client).send(0x9013e0, 0xc420112100, 0x0, 0x0, 0x0, 0xc420078060, 0x0, 0x1, 0xc420036d00)
	/usr/local/go/src/net/http/client.go:173 +0xfd
net/http.(*Client).Do(0x9013e0, 0xc420112100, 0x75df0a, 0x26, 0x0)
	/usr/local/go/src/net/http/client.go:602 +0x28d
net/http.(*Client).Get(0x9013e0, 0x75df0a, 0x26, 0x4d5c2d, 0x81bdc8, 0x81be08)
	/usr/local/go/src/net/http/client.go:393 +0xa7
net/http.Get(0x75df0a, 0x26, 0x0, 0xff, 0xff)
	/usr/local/go/src/net/http/client.go:367 +0x41
_/home/captain/workspace/go-plugins-helpers/authorization.TestActivate(0xc42010e0f0)
	/home/captain/workspace/go-plugins-helpers/authorization/api_test.go:43 +0x48
testing.tRunner(0xc42010e0f0, 0x767c90)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 27 [IO wait]:
internal/poll.runtime_pollWait(0x7f67de144eb0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420110718, 0x72, 0xffffffffffffff00, 0x8c8f00, 0x8c55c8)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420110718, 0xc420132000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420110700, 0xc420132000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:125 +0x18a
net.(*netFD).Read(0xc420110700, 0xc420132000, 0x1000, 0x1000, 0xc42006aa80, 0xc420036a68, 0x43595f)
	/usr/local/go/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc4200780a0, 0xc420132000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6d
net/http.(*persistConn).Read(0xc4200a8b40, 0xc420132000, 0x1000, 0x1000, 0xc420110700, 0xc42006aa00, 0xc420036b68)
	/usr/local/go/src/net/http/transport.go:1391 +0x140
bufio.(*Reader).fill(0xc4200888a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).Peek(0xc4200888a0, 0x1, 0xc420066900, 0xc420024c80, 0x900650, 0x8cc140, 0xc420074050)
	/usr/local/go/src/bufio/bufio.go:129 +0x3a
net/http.(*persistConn).readLoop(0xc4200a8b40)
	/usr/local/go/src/net/http/transport.go:1539 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1186 +0xa2e

goroutine 28 [select]:
net/http.(*persistConn).writeLoop(0xc4200a8b40)
	/usr/local/go/src/net/http/transport.go:1759 +0x165
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1187 +0xa53

rax    0xca
rbx    0x9020a0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x9021b0
rsi    0x0
rbp    0x7ffdf4f50dc0
rsp    0x7ffdf4f50d78
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0x0
r14    0x45c010
r15    0x0
rip    0x45e781
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	_/home/captain/workspace/go-plugins-helpers/authorization	600.009s  

Can anyone tell me what happened?Is there something wrong in the code?
Thank you so much.

**Comment by learnMachining** [comment]
I've found the solution. Just execute `go test -v` with root permission. Because a normal user doesn't have permission to create directories in /etc/docker/plugins. It's a shame that I ignored it.
